export const componentProps = {
  simpleBody: {
    styles: {
      textColor: { type: "color", value: "#ffffff" },
      buttonBgColor: { type: "color", value: "#10b981" },
      buttonTextColor: { type: "color", value: "#ffffff" },
      padding: { type: "space", value: "24px" },
      margin: { type: "space", value: "16px" },
      paddingHorizontal: { type: "space", value: "16px" },
      paddingVertical: { type: "space", value: "5px" },
      borderRadius: { type: "space", value: "5px" },
      mainBodyDisplay: { type: "display", value: "flex" },
      mainBodyJustify: { type: "display", value: "center" },
      mainBodyAlign: { type: "display", value: "center" },
      opacity: { type: "dimension", value: "0.5" },
      bodyHeight: { type: "dimension", value: "300px" },
    },
    content: {
      title: "Simple Body Title",
      subtitle: "Simple Body Subtitle",
      description: "This is a simple body description.",
      buttonText: "Click Me",
      bgImageSource: "/images/imbg.jpg",
    },
    added_elements: [],
  },
  hero1: {
    styles: {
      backgroundColor: { type: "color", value: "#000C18" }, // Dark purple
      textColor: { type: "color", value: "#ffffff" }, // Purple
      secondTextColor: { type: "color", value: "#4B0082" }, // Purple
      display: { type: "display", value: "flex" },
      flexDirection: { type: "display", value: "column" },
      alignItems: { type: "display", value: "center" },
      justifyContent: { type: "display", value: "center" },
      // height: { type: "dimension", value: "500px" },
      buttonBgColor: { type: "color", value: "#22c55e" },
      buttonTextColor: { type: "color", value: "#ffffff" },
      buttonPadding: { type: "space", value: "8px 16px" },
      navigationDisplay: { type: "display", value: "flex" },
      navigationJustify: { type: "display", value: "space-between" },
      navigationColor: { type: "color", value: "#1f2937" },
    },
    content: {
      title: "Make Your Payment Transaction Easy and",
      titleSecond:"¨Professional",
      description: "This is a hero description.",
      buttonText: "Click Me",
      items: ["Home", "About", "Contact"],
    },
    added_elements: [],
  },
  hero2: {
    styles: {
      textColor: { type: "color", value: "#ffffff" },
      buttonBgColor: { type: "color", value: "#22c55e" },
      buttonTextColor: { type: "color", value: "#ffffff" },
      display: { type: "display", value: "flex" },
      flexDirection: { type: "display", value: "column" },
      alignItems: { type: "display", value: "center" },
      justifyContent: { type: "display", value: "center" },
      height: { type: "dimension", value: "500px" },
      imageOpacity: { type: "dimension", value: "0.8" },
      buttonPadding: { type: "space", value: "8px 16px" },
      navigationDisplay: { type: "display", value: "flex" },
      navigationJustify: { type: "display", value: "space-between" },
      navigationColor: { type: "color", value: "#1f2937" },
    },
    content: {
      title: "Hero Title",
      description: "This is a hero description.",
      imgSrc: "/images/imbg.jpg",
      imageAlt: "Image description",
      buttonText: "Click Me",
      items: ["Home", "About", "Contact"],
    },
    added_elements: [],
  },
  hero3: {
    styles: {
      backgroundColor: { type: "color", value: "#ffffff" },
      textColor: { type: "color", value: "#1f2937" },
      display: { type: "display", value: "flex" },
      flexDirection: { type: "display", value: "row" },
      flexWrap: { type: "display", value: "nowrap" },
      alignItems: { type: "display", value: "items-start" },
      justifyContent: { type: "display", value: "justify-start" },
      imageHeight: { type: "dimension", value: "300px" },
      imageWidth: { type: "dimension", value: "100%" },
      imageBorderRadius: { type: "space", value: "10px" },
      buttonBgColor: { type: "color", value: "#22c55e" },
      buttonTextColor: { type: "color", value: "#ffffff" },
      buttonPadding: { type: "space", value: "8px 16px" },
      navigationDisplay: { type: "display", value: "flex" },
      navigationJustify: { type: "display", value: "space-between" },
      navigationColor: { type: "color", value: "#1f2937" },
    },
    content: {
      title: "Invest intelligently with our Innovative Solutions",
      description: "This is a hero description.",
      imageSrc: "/images/imbg.jpg",
      imageAlt: "Image description",
      buttonText: "Click Me",
      items: ["Home", "About", "Contact"],
    },
    added_elements: [],
  },
  // Add other components' default props here
};
